#!/usr/bin/env python3
"""Regression checks for Low Tide's modular crawler assembly and live equipment."""
import json
import math
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class CrawlerModuleTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.manifest = json.loads((ROOT / "Low_Tide_Kit/kit_manifest.json").read_text())
        cls.scene = json.loads((ROOT / "poc.scene").read_text())
        cls.drive = (ROOT / "scripts/crawler_drive.decay").read_text()
        cls.assembly = {a["name"]: a for a in cls.manifest["assembly"]}

    def test_clean_base_recipe_excludes_live_modules(self):
        # The clean GLB is generated by build_kit.py; it is not yet committed.
        builder = (ROOT / "Low_Tide_Kit/build_kit.py").read_text()
        self.assertIn("starter_crawler_clean_base.glb", builder)
        self.assertIn("'tank__123','antenna__125'", builder)
        self.assertIn("a['name'] not in detachable", builder)
        # Do not accidentally switch the playable scene to a missing GLB.
        crawler = next(e for e in self.scene["entities"] if e["id"] == "crawler")
        asset = crawler["components"]["sindri.model"]["asset"]
        self.assertTrue((ROOT / asset).is_file() or asset.endswith("starter_crawler_clean_base.glb"), asset)

    def test_clean_glb_removes_only_detachable_nodes(self):
        import importlib.util
        import struct
        spec = importlib.util.spec_from_file_location("cleaner", ROOT / "scripts/make_clean_crawler.py")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        original = (ROOT / "Low_Tide_Kit/starter_crawler_cutaway.glb").read_bytes()
        cleaned = module.clean(original)
        def reachable_names(blob):
            doc = json.loads(module.chunks(blob)[0][1])
            seen = set()
            def visit(i):
                if i in seen:
                    return
                seen.add(i)
                for child in doc["nodes"][i].get("children", []):
                    visit(child)
            for scene in doc["scenes"]:
                for root in scene.get("nodes", []):
                    visit(root)
            return {doc["nodes"][i].get("name") for i in seen}
        before, after = reachable_names(original), reachable_names(cleaned)
        self.assertIn("tank__123", before)
        self.assertNotIn("antenna__125", before)
        self.assertEqual(before - after, {"tank__123", *(
            name for name in before if name and (
                name.startswith("SOCKET_tank__123_") or
                name.startswith("SOCKET_antenna__125_")
            )
        )})
        self.assertEqual(struct.unpack_from("<I", cleaned, 8)[0], len(cleaned))

    def test_build_mode_controls_remain_usable(self):
        self.assertIn("sync_mode_controls();", self.drive)
        self.assertIn("World.set_active(this.cargo_button, this.build_mode)", self.drive)
        self.assertIn("World.set_active(this.tank_button, this.build_mode)", self.drive)
        self.assertIn("World.set_active(this.antenna_button, this.build_mode)", self.drive)
        self.assertIn("World.set_active(this.reset_button, !this.build_mode)", self.drive)
        equipment = self.drive.index('Input.just_pressed("Digit1")')
        pause = self.drive.index("if this.build_mode {", equipment)
        self.assertLess(equipment, pause, "Equipment must work before driving is paused")

    def test_mobile_button_labels(self):
        scene = json.loads((ROOT / "poc.scene").read_text())
        by_id = {e["id"]: e for e in scene["entities"]}
        for key in ("touch-build", "touch-reset", "touch-cargo", "touch-tank", "touch-antenna"):
            button = by_id[key]
            self.assertIn("sindri.ui.text", button["components"])
            self.assertIn("sindri.ui.button", button["components"])
            self.assertEqual(button["components"]["sindri.ui.text"]["text"], button["components"]["sindri.ui.button"]["label"])
            self.assertTrue(button["components"]["sindri.ui.text"]["font"])
            self.assertNotIn(key + "-label", by_id)
        css = (ROOT / "assets/ui/hud.weave").read_text()
        self.assertNotIn("\n    width:", css)
        self.assertNotIn("\n    height:", css)
        self.assertNotIn(" x:", css)

    def test_responsive_weave_hud(self):
        scene = json.loads((ROOT / "poc.scene").read_text())
        by_id = {e["id"]: e for e in scene["entities"]}
        for key in ("touch-build", "touch-reset", "touch-cargo", "touch-tank", "touch-antenna"):
            self.assertIn("weave.style", by_id[key]["components"])
            self.assertIn("sindri.ui.button", by_id[key]["components"])
        manifest = (ROOT / "sindri.toml").read_text()
        self.assertIn('assets/ui/hud.weave', manifest)
        css = (ROOT / "assets/ui/hud.weave").read_text()
        self.assertIn("@media (orientation: portrait)", css)
        self.assertIn("@media (max-height: 500px)", css)

    def test_floorplan_build_camera_mode(self):
        scene = json.loads((ROOT / "poc.scene").read_text())
        by_name = {e["name"]: e for e in scene["entities"]}
        camera = by_name["Crawler floorplan camera"]
        self.assertEqual(camera["components"]["sindri.camera"]["projection"], "orthographic")
        self.assertEqual(camera["components"]["sindri.camera"]["fit"], "shorter")
        self.assertTrue(camera["disabled"])
        self.assertIn("sindri.ui.button", by_name["Toggle build mode"]["components"])
        self.assertIn("World.set_parent(this.floorplan_camera, this.entity)", self.drive)
        self.assertIn("World.set_active(this.gameplay_camera, !this.build_mode)", self.drive)
        self.assertIn("World.set_active(this.floorplan_camera, this.build_mode)", self.drive)
        self.assertIn("if this.build_mode {", self.drive)

    def test_touch_equipment_controls(self):
        scene = json.loads((ROOT / "poc.scene").read_text())
        by_name = {entity["name"]: entity for entity in scene["entities"]}
        for label, field in (("cargo", "cargo_button"), ("tank", "tank_button"), ("antenna", "antenna_button")):
            entity = by_name[f"Toggle {label}"]
            self.assertIn("sindri.ui.button", entity["components"])
            self.assertIn(f"Ui.is_pressed(this.{field})", self.drive)

    def test_equipment_toggle_controls(self):
        for key, entity, state in (
            ("Digit1", "cargo", "cargo_installed"),
            ("Digit2", "tank", "tank_installed"),
            ("Digit3", "antenna", "antenna_installed"),
        ):
            self.assertIn(f'Input.just_pressed("{key}")', self.drive)
            self.assertIn(f"World.set_active(this.{entity}, this.{state})", self.drive)
        self.assertIn("World.set_parent(part, this.entity)", self.drive)

    def test_module_assets_exist(self):
        for item in self.manifest["assembly"]:
            asset = ROOT / "Low_Tide_Kit/modules" / (item["asset"] + ".glb")
            self.assertTrue(asset.is_file(), f"Missing {asset}")

    def test_live_module_offsets_match_manifest(self):
        # Each module's local transform is derived from the kit's Z-up source axes.
        mounts = {
            "fuel-module": "tank__123",
            "antenna-module": "antenna__125",
        }
        entities = {e["id"]: e for e in self.scene["entities"]}
        for entity_id, mount_name in mounts.items():
            x, y, z = self.assembly[mount_name]["position"]
            expected = [x, z, -y]
            entity = entities[entity_id]
            self.assertEqual(entity["transform_3d"]["position"], expected)
            self.assertIn(f"Vec3({x}, {z}, {-y})", self.drive)

    def test_attached_equipment_uses_local_transform(self):
        self.assertIn("World.set_parent(part, this.entity)", self.drive)
        self.assertIn("part.transform.position = offset", self.drive)

    def test_crawler_steering_sign_regression(self):
        self.assertIn("this.transform.yaw -= steering * turn_speed * dt * sign(throttle)", self.drive)

    def test_static_builder_preserves_scene_and_uses_y_up(self):
        import importlib.util
        path = ROOT / "scripts/build_modular_crawler.py"
        spec = importlib.util.spec_from_file_location("crawler_builder", path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        layout = json.loads((ROOT / "crawler/layout.json").read_text())
        result = module.build(self.manifest, self.scene, layout)
        self.assertFalse(any(e["id"] == "crawler" for e in result["entities"]))
        entities = {e["name"]: e for e in result["entities"]}
        for name in ("tank__123", "crate__119"):
            item = self.assembly[name]
            x, y, z = item["position"]
            self.assertEqual(entities[f"Module: {name} ({item['asset']})"]["transform_3d"]["position"], [x, z, -y])
        self.assertFalse(any(e["name"].startswith("Module: tank__124") for e in result["entities"]))
        self.assertFalse(any(e["name"].startswith("Module: antenna__125") for e in result["entities"]))


if __name__ == "__main__":
    unittest.main()
