#!/usr/bin/env python3
"""Regression checks for Low Tide's modular crawler assembly and live equipment."""
import json
import math
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class CrawlerModuleTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.manifest = json.loads((ROOT / "Low_Tide_Kit/kit_manifest.json").read_text())
        cls.scene = json.loads((ROOT / "poc.scene").read_text())
        cls.drive = (ROOT / "scripts/crawler_drive.decay").read_text()
        cls.assembly = {a["name"]: a for a in cls.manifest["assembly"]}

    def test_clean_base_recipe_excludes_live_modules(self):
        # The clean GLB is generated by build_kit.py; it is not yet committed.
        builder = (ROOT / "Low_Tide_Kit/build_kit.py").read_text()
        self.assertIn("starter_crawler_clean_base.glb", builder)
        self.assertIn("'tank__123','antenna__125'", builder)
        self.assertIn("a['name'] not in detachable", builder)
        # Do not accidentally switch the playable scene to a missing GLB.
        crawler = next(e for e in self.scene["entities"] if e["id"] == "crawler")
        asset = crawler["components"]["sindri.model"]["asset"]
        self.assertTrue((ROOT / asset).is_file() or asset.endswith("starter_crawler_clean_base.glb"), asset)

    def test_clean_glb_removes_only_detachable_nodes(self):
        import importlib.util
        import struct
        spec = importlib.util.spec_from_file_location("cleaner", ROOT / "scripts/make_clean_crawler.py")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        original = (ROOT / "Low_Tide_Kit/starter_crawler_cutaway.glb").read_bytes()
        cleaned = module.clean(original)
        def reachable_names(blob):
            doc = json.loads(module.chunks(blob)[0][1])
            seen = set()
            def visit(i):
                if i in seen:
                    return
                seen.add(i)
                for child in doc["nodes"][i].get("children", []):
                    visit(child)
            for scene in doc["scenes"]:
                for root in scene.get("nodes", []):
                    visit(root)
            return {doc["nodes"][i].get("name") for i in seen}
        before, after = reachable_names(original), reachable_names(cleaned)
        self.assertIn("tank__123", before)
        self.assertNotIn("antenna__125", before)
        self.assertEqual(before - after, {"tank__123", *(
            name for name in before if name and (
                name.startswith("SOCKET_tank__123_") or
                name.startswith("SOCKET_antenna__125_")
            )
        )})
        self.assertEqual(struct.unpack_from("<I", cleaned, 8)[0], len(cleaned))

    def test_module_assets_exist(self):
        for item in self.manifest["assembly"]:
            asset = ROOT / "Low_Tide_Kit/modules" / (item["asset"] + ".glb")
            self.assertTrue(asset.is_file(), f"Missing {asset}")

    def test_live_module_offsets_match_manifest(self):
        # Each module's local transform is derived from the kit's Z-up source axes.
        mounts = {
            "fuel-module": "tank__123",
            "antenna-module": "antenna__125",
        }
        entities = {e["id"]: e for e in self.scene["entities"]}
        for entity_id, mount_name in mounts.items():
            x, y, z = self.assembly[mount_name]["position"]
            expected = [x, z, -y]
            entity = entities[entity_id]
            self.assertEqual(entity["transform_3d"]["position"], expected)
            self.assertIn(f"Vec3({x}, {z}, {-y})", self.drive)

    def test_attached_equipment_uses_local_transform(self):
        self.assertIn("World.set_parent(part, this.entity)", self.drive)
        self.assertIn("part.transform.position = offset", self.drive)

    def test_crawler_steering_sign_regression(self):
        self.assertIn("this.transform.yaw -= steering * turn_speed * dt * sign(throttle)", self.drive)

    def test_static_builder_preserves_scene_and_uses_y_up(self):
        import importlib.util
        path = ROOT / "scripts/build_modular_crawler.py"
        spec = importlib.util.spec_from_file_location("crawler_builder", path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        layout = json.loads((ROOT / "crawler/layout.json").read_text())
        result = module.build(self.manifest, self.scene, layout)
        self.assertFalse(any(e["id"] == "crawler" for e in result["entities"]))
        entities = {e["name"]: e for e in result["entities"]}
        for name in ("tank__123", "antenna__125", "crate__119"):
            item = self.assembly[name]
            x, y, z = item["position"]
            self.assertEqual(entities[f"Module: {name} ({item['asset']})"]["transform_3d"]["position"], [x, z, -y])
        self.assertFalse(any(e["name"].startswith("Module: tank__124") for e in result["entities"]))


if __name__ == "__main__":
    unittest.main()
